const grafo = {
    nodes: [
        { id: "A", x: 250, y: 50 },
        { id: "B", x: 225, y: 120 },
        { id: "C", x: 350, y: 120 },
        { id: "D", x: 100, y: 190 },
        { id: "E", x: 250, y: 190 },
        { id: "F", x: 400, y: 190 },
        { id: "G", x: 150, y: 260 },
        { id: "H", x: 300, y: 260 },
        { id: "I", x: 450, y: 260 },
        { id: "J", x: 50,  y: 330 },
        { id: "K", x: 200, y: 250 },
        { id: "L", x: 350, y: 330 },
        { id: "M", x: 100, y: 400 },
        { id: "N", x: 250, y: 400 },
        { id: "O", x: 400, y: 400 },
        { id: "P", x: 250, y: 470 }
    ],
    links: [
        { source: "A", target: "B" },
        { source: "A", target: "C" },
        { source: "B", target: "D" },
        { source: "B", target: "E" },
        { source: "C", target: "F" },
        { source: "D", target: "G" },
        { source: "E", target: "H" },
        { source: "F", target: "I" },
        { source: "G", target: "J" },
        { source: "G", target: "K" },
        { source: "H", target: "L" },
        { source: "I", target: "L" },
        { source: "J", target: "M" },
        { source: "K", target: "N" },
        { source: "L", target: "O" },
        { source: "M", target: "P" },
        { source: "N", target: "P" },
        { source: "O", target: "P" },
        { source: "A", target: "D" },
        { source: "C", target: "H" },
        { source: "D", target: "K" },
        { source: "F", target: "H" },
        { source: "H", target: "N" },
        { source: "I", target: "O" },
    ]
};